// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | ValueCreationPlaybookSlice
  | HeroWithQuoteSlice
  | InvestmentTimelineSlice
  | CtaSlice
  | SectorExpertiseSlice
  | StepJourneySlice
  | HeroSlice
  | UpdatedHeroSectionSlice
  | HeroImageBackgroundSlice
  | StoryTestimonialsSlice
  | MeetTeamSlice
  | InvestmentHeroSlice
  | ThreeContentCardsSlice
  | ThreeRoundImagesSlice
  | MutedBackgroundContentSlice
  | SideHeadingContentSlice
  | ImageHeadingToggleSlice
  | ContentHeadingSlice
  | ReuseableCardsSlice
  | RoundedImageContentSlice
  | ScrollCardsSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ValueCreationPlaybookSlice
  | InvestmentTimelineSlice
  | HeroWithQuoteSlice
  | CtaSlice
  | SectorExpertiseSlice
  | StepJourneySlice
  | HeroSlice
  | UpdatedHeroSectionSlice
  | HeroImageBackgroundSlice
  | StoryTestimonialsSlice
  | MeetTeamSlice
  | InvestmentHeroSlice
  | ThreeContentCardsSlice
  | ThreeRoundImagesSlice
  | MutedBackgroundContentSlice
  | SideHeadingContentSlice
  | ImageHeadingToggleSlice
  | ContentHeadingSlice
  | ReuseableCardsSlice
  | RoundedImageContentSlice
  | ScrollCardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HomepageDocument | PageDocument;

/**
 * Primary content in *ContentHeading → Default → Primary*
 */
export interface ContentHeadingSliceDefaultPrimary {
  /**
   * Main Content field in *ContentHeading → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.default.primary.main_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_content: prismic.RichTextField;
}

/**
 * Default variation for ContentHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentHeading → Content Narrow Container → Primary*
 */
export interface ContentHeadingSliceContentNarrowContainerPrimary {
  /**
   * Main Content field in *ContentHeading → Content Narrow Container → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.contentNarrowContainer.primary.main_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_content: prismic.RichTextField;
}

/**
 * Content Narrow Container variation for ContentHeading Slice
 *
 * - **API ID**: `contentNarrowContainer`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeadingSliceContentNarrowContainer =
  prismic.SharedSliceVariation<
    "contentNarrowContainer",
    Simplify<ContentHeadingSliceContentNarrowContainerPrimary>,
    never
  >;

/**
 * Slice variation for *ContentHeading*
 */
type ContentHeadingSliceVariation =
  | ContentHeadingSliceDefault
  | ContentHeadingSliceContentNarrowContainer;

/**
 * ContentHeading Shared Slice
 *
 * - **API ID**: `content_heading`
 * - **Description**: ContentHeading
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeadingSlice = prismic.SharedSlice<
  "content_heading",
  ContentHeadingSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Heading field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Excerpt field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Primary Button Label field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Label field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Tag field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Excerpt field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Primary Button Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroImageBackground → Default → Primary*
 */
export interface HeroImageBackgroundSliceDefaultPrimary {
  /**
   * Background Image field in *HeroImageBackground → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image_background.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *HeroImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image_background.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *HeroImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image_background.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Primary Button Link field in *HeroImageBackground → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image_background.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroImageBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroImageBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroImageBackground*
 */
type HeroImageBackgroundSliceVariation = HeroImageBackgroundSliceDefault;

/**
 * HeroImageBackground Shared Slice
 *
 * - **API ID**: `hero_image_background`
 * - **Description**: HeroImageBackground
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroImageBackgroundSlice = prismic.SharedSlice<
  "hero_image_background",
  HeroImageBackgroundSliceVariation
>;

/**
 * Item in *HeroWithQuote → Default → Primary → Features*
 */
export interface HeroWithQuoteSliceDefaultPrimaryFeaturesItem {
  /**
   * Title field in *HeroWithQuote → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroWithQuote → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *HeroWithQuote → Default → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "Focused Strategy" | "US-Based Focus" | "Stable EBITDA"
  >;
}

/**
 * Primary content in *HeroWithQuote → Default → Primary*
 */
export interface HeroWithQuoteSliceDefaultPrimary {
  /**
   * Heading field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Intro field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;

  /**
   * Body field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Quote field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote: prismic.KeyTextField;

  /**
   * Author Name field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Title field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.author_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_title: prismic.KeyTextField;

  /**
   * Features field in *HeroWithQuote → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_quote.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<HeroWithQuoteSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for HeroWithQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithQuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithQuote*
 */
type HeroWithQuoteSliceVariation = HeroWithQuoteSliceDefault;

/**
 * HeroWithQuote Shared Slice
 *
 * - **API ID**: `hero_with_quote`
 * - **Description**: HeroWithQuote
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithQuoteSlice = prismic.SharedSlice<
  "hero_with_quote",
  HeroWithQuoteSliceVariation
>;

/**
 * Item in *ImageHeadingToggle → Default → Primary → faq*
 */
export interface ImageHeadingToggleSliceDefaultPrimaryFaqItem {
  /**
   * Question field in *ImageHeadingToggle → Default → Primary → faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_heading_toggle.default.primary.faq[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *ImageHeadingToggle → Default → Primary → faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_heading_toggle.default.primary.faq[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *ImageHeadingToggle → Default → Primary*
 */
export interface ImageHeadingToggleSliceDefaultPrimary {
  /**
   * Featured Image field in *ImageHeadingToggle → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_heading_toggle.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageHeadingToggle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_heading_toggle.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ImageHeadingToggle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_heading_toggle.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * faq field in *ImageHeadingToggle → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_heading_toggle.default.primary.faq[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq: prismic.GroupField<
    Simplify<ImageHeadingToggleSliceDefaultPrimaryFaqItem>
  >;
}

/**
 * Default variation for ImageHeadingToggle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageHeadingToggleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageHeadingToggleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageHeadingToggle*
 */
type ImageHeadingToggleSliceVariation = ImageHeadingToggleSliceDefault;

/**
 * ImageHeadingToggle Shared Slice
 *
 * - **API ID**: `image_heading_toggle`
 * - **Description**: ImageHeadingToggle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageHeadingToggleSlice = prismic.SharedSlice<
  "image_heading_toggle",
  ImageHeadingToggleSliceVariation
>;

/**
 * Primary content in *InvestmentHero → Default → Primary*
 */
export interface InvestmentHeroSliceDefaultPrimary {
  /**
   * Background Image field in *InvestmentHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: investment_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *InvestmentHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investment_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *InvestmentHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: investment_hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * PDF GUIDE field in *InvestmentHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: investment_hero.default.primary.pdf_guide
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  pdf_guide: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Guide Image field in *InvestmentHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: investment_hero.default.primary.guide_image
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  guide_image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Featured Image field in *InvestmentHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: investment_hero.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;
}

/**
 * Default variation for InvestmentHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InvestmentHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InvestmentHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InvestmentHero*
 */
type InvestmentHeroSliceVariation = InvestmentHeroSliceDefault;

/**
 * InvestmentHero Shared Slice
 *
 * - **API ID**: `investment_hero`
 * - **Description**: InvestmentHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InvestmentHeroSlice = prismic.SharedSlice<
  "investment_hero",
  InvestmentHeroSliceVariation
>;

/**
 * Default variation for InvestmentTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InvestmentTimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *InvestmentTimeline*
 */
type InvestmentTimelineSliceVariation = InvestmentTimelineSliceDefault;

/**
 * InvestmentTimeline Shared Slice
 *
 * - **API ID**: `investment_timeline`
 * - **Description**: InvestmentTimeline
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InvestmentTimelineSlice = prismic.SharedSlice<
  "investment_timeline",
  InvestmentTimelineSliceVariation
>;

/**
 * Item in *MeetTeam → Default → Primary → Teams*
 */
export interface MeetTeamSliceDefaultPrimaryTeamsItem {
  /**
   * Person Image field in *MeetTeam → Default → Primary → Teams*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.teams[].person_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  person_image: prismic.ImageField<never>;

  /**
   * Person Name field in *MeetTeam → Default → Primary → Teams*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.teams[].person_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  person_name: prismic.KeyTextField;

  /**
   * Person Designation field in *MeetTeam → Default → Primary → Teams*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.teams[].person_designation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  person_designation: prismic.KeyTextField;

  /**
   * Person Company field in *MeetTeam → Default → Primary → Teams*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.teams[].person_company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  person_company: prismic.KeyTextField;

  /**
   * Content field in *MeetTeam → Default → Primary → Teams*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.teams[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *MeetTeam → Default → Primary*
 */
export interface MeetTeamSliceDefaultPrimary {
  /**
   * Teams field in *MeetTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.teams[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  teams: prismic.GroupField<Simplify<MeetTeamSliceDefaultPrimaryTeamsItem>>;

  /**
   * Heading field in *MeetTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for MeetTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MeetTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MeetTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MeetTeam*
 */
type MeetTeamSliceVariation = MeetTeamSliceDefault;

/**
 * MeetTeam Shared Slice
 *
 * - **API ID**: `meet_team`
 * - **Description**: MeetTeam
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MeetTeamSlice = prismic.SharedSlice<
  "meet_team",
  MeetTeamSliceVariation
>;

/**
 * Primary content in *MutedBackgroundContent → Default → Primary*
 */
export interface MutedBackgroundContentSliceDefaultPrimary {
  /**
   * Content field in *MutedBackgroundContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: muted_background_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Author field in *MutedBackgroundContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: muted_background_content.default.primary.author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;
}

/**
 * Default variation for MutedBackgroundContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MutedBackgroundContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MutedBackgroundContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MutedBackgroundContent*
 */
type MutedBackgroundContentSliceVariation = MutedBackgroundContentSliceDefault;

/**
 * MutedBackgroundContent Shared Slice
 *
 * - **API ID**: `muted_background_content`
 * - **Description**: MutedBackgroundContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MutedBackgroundContentSlice = prismic.SharedSlice<
  "muted_background_content",
  MutedBackgroundContentSliceVariation
>;

/**
 * Item in *ReuseableCards → Default → Primary → Cards*
 */
export interface ReuseableCardsSliceDefaultPrimaryCardsItem {
  /**
   * Card Heading field in *ReuseableCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reuseable_cards.default.primary.cards[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_heading: prismic.KeyTextField;

  /**
   * Card Description field in *ReuseableCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reuseable_cards.default.primary.cards[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_description: prismic.KeyTextField;
}

/**
 * Primary content in *ReuseableCards → Default → Primary*
 */
export interface ReuseableCardsSliceDefaultPrimary {
  /**
   * Heading field in *ReuseableCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reuseable_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Cards field in *ReuseableCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reuseable_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<ReuseableCardsSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for ReuseableCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReuseableCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReuseableCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReuseableCards*
 */
type ReuseableCardsSliceVariation = ReuseableCardsSliceDefault;

/**
 * ReuseableCards Shared Slice
 *
 * - **API ID**: `reuseable_cards`
 * - **Description**: ReuseableCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReuseableCardsSlice = prismic.SharedSlice<
  "reuseable_cards",
  ReuseableCardsSliceVariation
>;

/**
 * Primary content in *RoundedImageContent → Default → Primary*
 */
export interface RoundedImageContentSliceDefaultPrimary {
  /**
   * Heading field in *RoundedImageContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rounded_image_content.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *RoundedImageContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rounded_image_content.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Button Link field in *RoundedImageContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rounded_image_content.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Main Image field in *RoundedImageContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rounded_image_content.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;
}

/**
 * Default variation for RoundedImageContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoundedImageContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoundedImageContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoundedImageContent*
 */
type RoundedImageContentSliceVariation = RoundedImageContentSliceDefault;

/**
 * RoundedImageContent Shared Slice
 *
 * - **API ID**: `rounded_image_content`
 * - **Description**: RoundedImageContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoundedImageContentSlice = prismic.SharedSlice<
  "rounded_image_content",
  RoundedImageContentSliceVariation
>;

/**
 * Item in *ScrollCards → Default → Primary → Cards*
 */
export interface ScrollCardsSliceDefaultPrimaryCardsItem {
  /**
   * Investor Quote field in *ScrollCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_cards.default.primary.cards[].investor_quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  investor_quote: prismic.KeyTextField;

  /**
   * Investor Name field in *ScrollCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_cards.default.primary.cards[].investor_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  investor_name: prismic.KeyTextField;

  /**
   * Investor Designation field in *ScrollCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_cards.default.primary.cards[].investor_designation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  investor_designation: prismic.KeyTextField;

  /**
   * Investor Rating field in *ScrollCards → Default → Primary → Cards*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_cards.default.primary.cards[].investor_rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  investor_rating: prismic.NumberField;
}

/**
 * Primary content in *ScrollCards → Default → Primary*
 */
export interface ScrollCardsSliceDefaultPrimary {
  /**
   * Heading field in *ScrollCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Cards field in *ScrollCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<ScrollCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for ScrollCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScrollCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScrollCards*
 */
type ScrollCardsSliceVariation = ScrollCardsSliceDefault;

/**
 * ScrollCards Shared Slice
 *
 * - **API ID**: `scroll_cards`
 * - **Description**: ScrollCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollCardsSlice = prismic.SharedSlice<
  "scroll_cards",
  ScrollCardsSliceVariation
>;

/**
 * Item in *SectorExpertise → Default → Primary → Sector*
 */
export interface SectorExpertiseSliceDefaultPrimarySectorItem {
  /**
   * Icon field in *SectorExpertise → Default → Primary → Sector*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Manufacturing
   * - **API ID Path**: sector_expertise.default.primary.sector[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "Manufacturing"
    | "Business Services"
    | "Healthcare"
    | "Aerospace & Defense",
    "filled"
  >;

  /**
   * Name field in *SectorExpertise → Default → Primary → Sector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.sector[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *SectorExpertise → Default → Primary → Sector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.sector[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *SectorExpertise → Default → Primary*
 */
export interface SectorExpertiseSliceDefaultPrimary {
  /**
   * Heading field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Excerpt field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Target Profile Label field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.target_profile_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  target_profile_label: prismic.KeyTextField;

  /**
   * Revenue field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.revenue
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  revenue: prismic.KeyTextField;

  /**
   * Ownership field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.ownership
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ownership: prismic.KeyTextField;

  /**
   * Ebitda field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.ebitda
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ebitda: prismic.KeyTextField;

  /**
   * Geography field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.geography
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  geography: prismic.KeyTextField;

  /**
   * Sector field in *SectorExpertise → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_expertise.default.primary.sector[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sector: prismic.GroupField<
    Simplify<SectorExpertiseSliceDefaultPrimarySectorItem>
  >;
}

/**
 * Default variation for SectorExpertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectorExpertiseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectorExpertiseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectorExpertise*
 */
type SectorExpertiseSliceVariation = SectorExpertiseSliceDefault;

/**
 * SectorExpertise Shared Slice
 *
 * - **API ID**: `sector_expertise`
 * - **Description**: SectorExpertise
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectorExpertiseSlice = prismic.SharedSlice<
  "sector_expertise",
  SectorExpertiseSliceVariation
>;

/**
 * Primary content in *SideHeadingContent → Default → Primary*
 */
export interface SideHeadingContentSliceDefaultPrimary {
  /**
   * Heading field in *SideHeadingContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_heading_content.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *SideHeadingContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_heading_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *SideHeadingContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: side_heading_content.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SideHeadingContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideHeadingContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SideHeadingContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SideHeadingContent*
 */
type SideHeadingContentSliceVariation = SideHeadingContentSliceDefault;

/**
 * SideHeadingContent Shared Slice
 *
 * - **API ID**: `side_heading_content`
 * - **Description**: SideHeadingContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideHeadingContentSlice = prismic.SharedSlice<
  "side_heading_content",
  SideHeadingContentSliceVariation
>;

/**
 * Item in *StepJourney → Default → Primary → Steps*
 */
export interface StepJourneySliceDefaultPrimaryStepsItem {
  /**
   * Title field in *StepJourney → Default → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: step_journey.default.primary.steps[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *StepJourney → Default → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: step_journey.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *StepJourney → Default → Primary → Steps*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: step_journey.default.primary.steps[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "Identify" | "Acquire" | "Optimize" | "Scale" | "Exit"
  >;
}

/**
 * Primary content in *StepJourney → Default → Primary*
 */
export interface StepJourneySliceDefaultPrimary {
  /**
   * Heading field in *StepJourney → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: step_journey.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Excerpt field in *StepJourney → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: step_journey.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Steps field in *StepJourney → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: step_journey.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<Simplify<StepJourneySliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for StepJourney Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepJourneySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepJourneySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StepJourney*
 */
type StepJourneySliceVariation = StepJourneySliceDefault;

/**
 * StepJourney Shared Slice
 *
 * - **API ID**: `step_journey`
 * - **Description**: StepJourney
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepJourneySlice = prismic.SharedSlice<
  "step_journey",
  StepJourneySliceVariation
>;

/**
 * Primary content in *StoryTestimonials → Default → Primary*
 */
export interface StoryTestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *StoryTestimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *StoryTestimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_testimonials.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Founder Name field in *StoryTestimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_testimonials.default.primary.founder_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  founder_name: prismic.KeyTextField;

  /**
   * Founder Designation field in *StoryTestimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_testimonials.default.primary.founder_designation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  founder_designation: prismic.KeyTextField;

  /**
   * Tagline field in *StoryTestimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_testimonials.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for StoryTestimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StoryTestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoryTestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StoryTestimonials*
 */
type StoryTestimonialsSliceVariation = StoryTestimonialsSliceDefault;

/**
 * StoryTestimonials Shared Slice
 *
 * - **API ID**: `story_testimonials`
 * - **Description**: StoryTestimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StoryTestimonialsSlice = prismic.SharedSlice<
  "story_testimonials",
  StoryTestimonialsSliceVariation
>;

/**
 * Item in *ThreeContentCards → Default → Primary → Cards*
 */
export interface ThreeContentCardsSliceDefaultPrimaryCardsItem {
  /**
   * Heading field in *ThreeContentCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_content_cards.default.primary.cards[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *ThreeContentCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_content_cards.default.primary.cards[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Card Image field in *ThreeContentCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_content_cards.default.primary.cards[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;
}

/**
 * Primary content in *ThreeContentCards → Default → Primary*
 */
export interface ThreeContentCardsSliceDefaultPrimary {
  /**
   * Heading field in *ThreeContentCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_content_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ThreeContentCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_content_cards.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Cards field in *ThreeContentCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: three_content_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<ThreeContentCardsSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for ThreeContentCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeContentCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThreeContentCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThreeContentCards*
 */
type ThreeContentCardsSliceVariation = ThreeContentCardsSliceDefault;

/**
 * ThreeContentCards Shared Slice
 *
 * - **API ID**: `three_content_cards`
 * - **Description**: ThreeContentCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeContentCardsSlice = prismic.SharedSlice<
  "three_content_cards",
  ThreeContentCardsSliceVariation
>;

/**
 * Item in *ThreeRoundImages → Default → Primary → cards*
 */
export interface ThreeRoundImagesSliceDefaultPrimaryCardsItem {
  /**
   * Card Image field in *ThreeRoundImages → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_round_images.default.primary.cards[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Card Title field in *ThreeRoundImages → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_round_images.default.primary.cards[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;
}

/**
 * Primary content in *ThreeRoundImages → Default → Primary*
 */
export interface ThreeRoundImagesSliceDefaultPrimary {
  /**
   * Heading field in *ThreeRoundImages → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_round_images.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Button Link field in *ThreeRoundImages → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_round_images.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * cards field in *ThreeRoundImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: three_round_images.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<ThreeRoundImagesSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for ThreeRoundImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeRoundImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThreeRoundImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThreeRoundImages*
 */
type ThreeRoundImagesSliceVariation = ThreeRoundImagesSliceDefault;

/**
 * ThreeRoundImages Shared Slice
 *
 * - **API ID**: `three_round_images`
 * - **Description**: ThreeRoundImages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeRoundImagesSlice = prismic.SharedSlice<
  "three_round_images",
  ThreeRoundImagesSliceVariation
>;

/**
 * Primary content in *UpdatedHeroSection → Default → Primary*
 */
export interface UpdatedHeroSectionSliceDefaultPrimary {
  /**
   * Background Image field in *UpdatedHeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: updated_hero_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *UpdatedHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: updated_hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *UpdatedHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: updated_hero_section.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Content field in *UpdatedHeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: updated_hero_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *UpdatedHeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: updated_hero_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Title field in *UpdatedHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: updated_hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for UpdatedHeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UpdatedHeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UpdatedHeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *UpdatedHeroSection*
 */
type UpdatedHeroSectionSliceVariation = UpdatedHeroSectionSliceDefault;

/**
 * UpdatedHeroSection Shared Slice
 *
 * - **API ID**: `updated_hero_section`
 * - **Description**: UpdatedHeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UpdatedHeroSectionSlice = prismic.SharedSlice<
  "updated_hero_section",
  UpdatedHeroSectionSliceVariation
>;

/**
 * Default variation for ValueCreationPlaybook Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValueCreationPlaybookSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ValueCreationPlaybook*
 */
type ValueCreationPlaybookSliceVariation = ValueCreationPlaybookSliceDefault;

/**
 * ValueCreationPlaybook Shared Slice
 *
 * - **API ID**: `value_creation_playbook`
 * - **Description**: ValueCreationPlaybook
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValueCreationPlaybookSlice = prismic.SharedSlice<
  "value_creation_playbook",
  ValueCreationPlaybookSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentHeadingSlice,
      ContentHeadingSliceDefaultPrimary,
      ContentHeadingSliceContentNarrowContainerPrimary,
      ContentHeadingSliceVariation,
      ContentHeadingSliceDefault,
      ContentHeadingSliceContentNarrowContainer,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroImageBackgroundSlice,
      HeroImageBackgroundSliceDefaultPrimary,
      HeroImageBackgroundSliceVariation,
      HeroImageBackgroundSliceDefault,
      HeroWithQuoteSlice,
      HeroWithQuoteSliceDefaultPrimaryFeaturesItem,
      HeroWithQuoteSliceDefaultPrimary,
      HeroWithQuoteSliceVariation,
      HeroWithQuoteSliceDefault,
      ImageHeadingToggleSlice,
      ImageHeadingToggleSliceDefaultPrimaryFaqItem,
      ImageHeadingToggleSliceDefaultPrimary,
      ImageHeadingToggleSliceVariation,
      ImageHeadingToggleSliceDefault,
      InvestmentHeroSlice,
      InvestmentHeroSliceDefaultPrimary,
      InvestmentHeroSliceVariation,
      InvestmentHeroSliceDefault,
      InvestmentTimelineSlice,
      InvestmentTimelineSliceVariation,
      InvestmentTimelineSliceDefault,
      MeetTeamSlice,
      MeetTeamSliceDefaultPrimaryTeamsItem,
      MeetTeamSliceDefaultPrimary,
      MeetTeamSliceVariation,
      MeetTeamSliceDefault,
      MutedBackgroundContentSlice,
      MutedBackgroundContentSliceDefaultPrimary,
      MutedBackgroundContentSliceVariation,
      MutedBackgroundContentSliceDefault,
      ReuseableCardsSlice,
      ReuseableCardsSliceDefaultPrimaryCardsItem,
      ReuseableCardsSliceDefaultPrimary,
      ReuseableCardsSliceVariation,
      ReuseableCardsSliceDefault,
      RoundedImageContentSlice,
      RoundedImageContentSliceDefaultPrimary,
      RoundedImageContentSliceVariation,
      RoundedImageContentSliceDefault,
      ScrollCardsSlice,
      ScrollCardsSliceDefaultPrimaryCardsItem,
      ScrollCardsSliceDefaultPrimary,
      ScrollCardsSliceVariation,
      ScrollCardsSliceDefault,
      SectorExpertiseSlice,
      SectorExpertiseSliceDefaultPrimarySectorItem,
      SectorExpertiseSliceDefaultPrimary,
      SectorExpertiseSliceVariation,
      SectorExpertiseSliceDefault,
      SideHeadingContentSlice,
      SideHeadingContentSliceDefaultPrimary,
      SideHeadingContentSliceVariation,
      SideHeadingContentSliceDefault,
      StepJourneySlice,
      StepJourneySliceDefaultPrimaryStepsItem,
      StepJourneySliceDefaultPrimary,
      StepJourneySliceVariation,
      StepJourneySliceDefault,
      StoryTestimonialsSlice,
      StoryTestimonialsSliceDefaultPrimary,
      StoryTestimonialsSliceVariation,
      StoryTestimonialsSliceDefault,
      ThreeContentCardsSlice,
      ThreeContentCardsSliceDefaultPrimaryCardsItem,
      ThreeContentCardsSliceDefaultPrimary,
      ThreeContentCardsSliceVariation,
      ThreeContentCardsSliceDefault,
      ThreeRoundImagesSlice,
      ThreeRoundImagesSliceDefaultPrimaryCardsItem,
      ThreeRoundImagesSliceDefaultPrimary,
      ThreeRoundImagesSliceVariation,
      ThreeRoundImagesSliceDefault,
      UpdatedHeroSectionSlice,
      UpdatedHeroSectionSliceDefaultPrimary,
      UpdatedHeroSectionSliceVariation,
      UpdatedHeroSectionSliceDefault,
      ValueCreationPlaybookSlice,
      ValueCreationPlaybookSliceVariation,
      ValueCreationPlaybookSliceDefault,
    };
  }
}
