/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainSiteRouteRouteImport } from './routes/(main-site)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as SliceSimulatorIndexRouteImport } from './routes/slice-simulator/index'
import { Route as mainSiteIndexRouteImport } from './routes/(main-site)/index'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as ApiExitPreviewRouteImport } from './routes/api/exit-preview'
import { Route as dashboardadminRouteRouteImport } from './routes/(dashboard)/(admin)/route'
import { Route as mainSiteUidIndexRouteImport } from './routes/(main-site)/$uid/index'
import { Route as dashboardOnboardingIndexRouteImport } from './routes/(dashboard)/onboarding/index'
import { Route as dashboardDealsIndexRouteImport } from './routes/(dashboard)/deals/index'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as authVerifyEmailIndexRouteImport } from './routes/(auth)/verify-email/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/(auth)/reset-password/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiOnboardingSubmitRouteImport } from './routes/api/onboarding/submit'
import { Route as ApiDocumentsDownloadRouteImport } from './routes/api/documents/download'
import { Route as ApiDocumentsAccessRouteImport } from './routes/api/documents/access'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as mainSiteSectorsSectorIndexRouteImport } from './routes/(main-site)/sectors/$sector/index'
import { Route as mainSiteInvestmentsTypeIndexRouteImport } from './routes/(main-site)/investments/$type/index'
import { Route as dashboardProfileEditOnboardingIndexRouteImport } from './routes/(dashboard)/profile/edit-onboarding/index'
import { Route as dashboardProfileUserIdIndexRouteImport } from './routes/(dashboard)/profile/$userId/index'
import { Route as dashboardOnboardingEditIndexRouteImport } from './routes/(dashboard)/onboarding/edit/index'
import { Route as dashboardDealsDealIdIndexRouteImport } from './routes/(dashboard)/deals/$dealId/index'
import { Route as dashboardadminAdminIndexRouteImport } from './routes/(dashboard)/(admin)/admin/index'
import { Route as ApiOnboardingOnboardingIdStatusRouteImport } from './routes/api/onboarding/$onboardingId/status'
import { Route as ApiDocumentsDocumentIdStatusRouteImport } from './routes/api/documents/$documentId/status'
import { Route as dashboardadminAdminDealsIndexRouteImport } from './routes/(dashboard)/(admin)/admin/deals/index'
import { Route as dashboardadminAdminComplianceIndexRouteImport } from './routes/(dashboard)/(admin)/admin/compliance/index'
import { Route as dashboardadminAdminDealsNewIndexRouteImport } from './routes/(dashboard)/(admin)/admin/deals/new/index'
import { Route as dashboardadminAdminDealsDealIdIndexRouteImport } from './routes/(dashboard)/(admin)/admin/deals/$dealId/index'
import { Route as dashboardadminAdminDealsDealIdEditIndexRouteImport } from './routes/(dashboard)/(admin)/admin/deals/$dealId/edit/index'
import { Route as dashboardadminAdminDealsDealIdCurateIndexRouteImport } from './routes/(dashboard)/(admin)/admin/deals/$dealId/curate/index'
import { Route as dashboardadminAdminComplianceInvestorsIdIndexRouteImport } from './routes/(dashboard)/(admin)/admin/compliance/investors/$id/index'

const mainSiteRouteRoute = mainSiteRouteRouteImport.update({
  id: '/(main-site)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const SliceSimulatorIndexRoute = SliceSimulatorIndexRouteImport.update({
  id: '/slice-simulator/',
  path: '/slice-simulator/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainSiteIndexRoute = mainSiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainSiteRouteRoute,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExitPreviewRoute = ApiExitPreviewRouteImport.update({
  id: '/api/exit-preview',
  path: '/api/exit-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardadminRouteRoute = dashboardadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const mainSiteUidIndexRoute = mainSiteUidIndexRouteImport.update({
  id: '/$uid/',
  path: '/$uid/',
  getParentRoute: () => mainSiteRouteRoute,
} as any)
const dashboardOnboardingIndexRoute =
  dashboardOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardDealsIndexRoute = dashboardDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authVerifyEmailIndexRoute = authVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingSubmitRoute = ApiOnboardingSubmitRouteImport.update({
  id: '/api/onboarding/submit',
  path: '/api/onboarding/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDownloadRoute = ApiDocumentsDownloadRouteImport.update({
  id: '/api/documents/download',
  path: '/api/documents/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsAccessRoute = ApiDocumentsAccessRouteImport.update({
  id: '/api/documents/access',
  path: '/api/documents/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainSiteSectorsSectorIndexRoute =
  mainSiteSectorsSectorIndexRouteImport.update({
    id: '/sectors/$sector/',
    path: '/sectors/$sector/',
    getParentRoute: () => mainSiteRouteRoute,
  } as any)
const mainSiteInvestmentsTypeIndexRoute =
  mainSiteInvestmentsTypeIndexRouteImport.update({
    id: '/investments/$type/',
    path: '/investments/$type/',
    getParentRoute: () => mainSiteRouteRoute,
  } as any)
const dashboardProfileEditOnboardingIndexRoute =
  dashboardProfileEditOnboardingIndexRouteImport.update({
    id: '/profile/edit-onboarding/',
    path: '/profile/edit-onboarding/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardProfileUserIdIndexRoute =
  dashboardProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardOnboardingEditIndexRoute =
  dashboardOnboardingEditIndexRouteImport.update({
    id: '/onboarding/edit/',
    path: '/onboarding/edit/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardDealsDealIdIndexRoute =
  dashboardDealsDealIdIndexRouteImport.update({
    id: '/deals/$dealId/',
    path: '/deals/$dealId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardadminAdminIndexRoute =
  dashboardadminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const ApiOnboardingOnboardingIdStatusRoute =
  ApiOnboardingOnboardingIdStatusRouteImport.update({
    id: '/api/onboarding/$onboardingId/status',
    path: '/api/onboarding/$onboardingId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsDocumentIdStatusRoute =
  ApiDocumentsDocumentIdStatusRouteImport.update({
    id: '/api/documents/$documentId/status',
    path: '/api/documents/$documentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardadminAdminDealsIndexRoute =
  dashboardadminAdminDealsIndexRouteImport.update({
    id: '/admin/deals/',
    path: '/admin/deals/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const dashboardadminAdminComplianceIndexRoute =
  dashboardadminAdminComplianceIndexRouteImport.update({
    id: '/admin/compliance/',
    path: '/admin/compliance/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const dashboardadminAdminDealsNewIndexRoute =
  dashboardadminAdminDealsNewIndexRouteImport.update({
    id: '/admin/deals/new/',
    path: '/admin/deals/new/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const dashboardadminAdminDealsDealIdIndexRoute =
  dashboardadminAdminDealsDealIdIndexRouteImport.update({
    id: '/admin/deals/$dealId/',
    path: '/admin/deals/$dealId/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const dashboardadminAdminDealsDealIdEditIndexRoute =
  dashboardadminAdminDealsDealIdEditIndexRouteImport.update({
    id: '/admin/deals/$dealId/edit/',
    path: '/admin/deals/$dealId/edit/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const dashboardadminAdminDealsDealIdCurateIndexRoute =
  dashboardadminAdminDealsDealIdCurateIndexRouteImport.update({
    id: '/admin/deals/$dealId/curate/',
    path: '/admin/deals/$dealId/curate/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)
const dashboardadminAdminComplianceInvestorsIdIndexRoute =
  dashboardadminAdminComplianceInvestorsIdIndexRouteImport.update({
    id: '/admin/compliance/investors/$id/',
    path: '/admin/compliance/investors/$id/',
    getParentRoute: () => dashboardadminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/': typeof mainSiteIndexRoute
  '/slice-simulator/': typeof SliceSimulatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/access': typeof ApiDocumentsAccessRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/api/onboarding/submit': typeof ApiOnboardingSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/forgot-password/': typeof authForgotPasswordIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/reset-password/': typeof authResetPasswordIndexRoute
  '/verify-email/': typeof authVerifyEmailIndexRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/deals/': typeof dashboardDealsIndexRoute
  '/onboarding/': typeof dashboardOnboardingIndexRoute
  '/$uid/': typeof mainSiteUidIndexRoute
  '/api/documents/$documentId/status': typeof ApiDocumentsDocumentIdStatusRoute
  '/api/onboarding/$onboardingId/status': typeof ApiOnboardingOnboardingIdStatusRoute
  '/admin/': typeof dashboardadminAdminIndexRoute
  '/deals/$dealId/': typeof dashboardDealsDealIdIndexRoute
  '/onboarding/edit/': typeof dashboardOnboardingEditIndexRoute
  '/profile/$userId/': typeof dashboardProfileUserIdIndexRoute
  '/profile/edit-onboarding/': typeof dashboardProfileEditOnboardingIndexRoute
  '/investments/$type/': typeof mainSiteInvestmentsTypeIndexRoute
  '/sectors/$sector/': typeof mainSiteSectorsSectorIndexRoute
  '/admin/compliance/': typeof dashboardadminAdminComplianceIndexRoute
  '/admin/deals/': typeof dashboardadminAdminDealsIndexRoute
  '/admin/deals/$dealId/': typeof dashboardadminAdminDealsDealIdIndexRoute
  '/admin/deals/new/': typeof dashboardadminAdminDealsNewIndexRoute
  '/admin/compliance/investors/$id/': typeof dashboardadminAdminComplianceInvestorsIdIndexRoute
  '/admin/deals/$dealId/curate/': typeof dashboardadminAdminDealsDealIdCurateIndexRoute
  '/admin/deals/$dealId/edit/': typeof dashboardadminAdminDealsDealIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/': typeof mainSiteIndexRoute
  '/slice-simulator': typeof SliceSimulatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/access': typeof ApiDocumentsAccessRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/api/onboarding/submit': typeof ApiOnboardingSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/verify-email': typeof authVerifyEmailIndexRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/deals': typeof dashboardDealsIndexRoute
  '/onboarding': typeof dashboardOnboardingIndexRoute
  '/$uid': typeof mainSiteUidIndexRoute
  '/api/documents/$documentId/status': typeof ApiDocumentsDocumentIdStatusRoute
  '/api/onboarding/$onboardingId/status': typeof ApiOnboardingOnboardingIdStatusRoute
  '/admin': typeof dashboardadminAdminIndexRoute
  '/deals/$dealId': typeof dashboardDealsDealIdIndexRoute
  '/onboarding/edit': typeof dashboardOnboardingEditIndexRoute
  '/profile/$userId': typeof dashboardProfileUserIdIndexRoute
  '/profile/edit-onboarding': typeof dashboardProfileEditOnboardingIndexRoute
  '/investments/$type': typeof mainSiteInvestmentsTypeIndexRoute
  '/sectors/$sector': typeof mainSiteSectorsSectorIndexRoute
  '/admin/compliance': typeof dashboardadminAdminComplianceIndexRoute
  '/admin/deals': typeof dashboardadminAdminDealsIndexRoute
  '/admin/deals/$dealId': typeof dashboardadminAdminDealsDealIdIndexRoute
  '/admin/deals/new': typeof dashboardadminAdminDealsNewIndexRoute
  '/admin/compliance/investors/$id': typeof dashboardadminAdminComplianceInvestorsIdIndexRoute
  '/admin/deals/$dealId/curate': typeof dashboardadminAdminDealsDealIdCurateIndexRoute
  '/admin/deals/$dealId/edit': typeof dashboardadminAdminDealsDealIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(main-site)': typeof mainSiteRouteRouteWithChildren
  '/(dashboard)/(admin)': typeof dashboardadminRouteRouteWithChildren
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/(main-site)/': typeof mainSiteIndexRoute
  '/slice-simulator/': typeof SliceSimulatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/access': typeof ApiDocumentsAccessRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/api/onboarding/submit': typeof ApiOnboardingSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/verify-email/': typeof authVerifyEmailIndexRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(dashboard)/deals/': typeof dashboardDealsIndexRoute
  '/(dashboard)/onboarding/': typeof dashboardOnboardingIndexRoute
  '/(main-site)/$uid/': typeof mainSiteUidIndexRoute
  '/api/documents/$documentId/status': typeof ApiDocumentsDocumentIdStatusRoute
  '/api/onboarding/$onboardingId/status': typeof ApiOnboardingOnboardingIdStatusRoute
  '/(dashboard)/(admin)/admin/': typeof dashboardadminAdminIndexRoute
  '/(dashboard)/deals/$dealId/': typeof dashboardDealsDealIdIndexRoute
  '/(dashboard)/onboarding/edit/': typeof dashboardOnboardingEditIndexRoute
  '/(dashboard)/profile/$userId/': typeof dashboardProfileUserIdIndexRoute
  '/(dashboard)/profile/edit-onboarding/': typeof dashboardProfileEditOnboardingIndexRoute
  '/(main-site)/investments/$type/': typeof mainSiteInvestmentsTypeIndexRoute
  '/(main-site)/sectors/$sector/': typeof mainSiteSectorsSectorIndexRoute
  '/(dashboard)/(admin)/admin/compliance/': typeof dashboardadminAdminComplianceIndexRoute
  '/(dashboard)/(admin)/admin/deals/': typeof dashboardadminAdminDealsIndexRoute
  '/(dashboard)/(admin)/admin/deals/$dealId/': typeof dashboardadminAdminDealsDealIdIndexRoute
  '/(dashboard)/(admin)/admin/deals/new/': typeof dashboardadminAdminDealsNewIndexRoute
  '/(dashboard)/(admin)/admin/compliance/investors/$id/': typeof dashboardadminAdminComplianceInvestorsIdIndexRoute
  '/(dashboard)/(admin)/admin/deals/$dealId/curate/': typeof dashboardadminAdminDealsDealIdCurateIndexRoute
  '/(dashboard)/(admin)/admin/deals/$dealId/edit/': typeof dashboardadminAdminDealsDealIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/'
    | '/slice-simulator/'
    | '/api/auth/$'
    | '/api/documents/access'
    | '/api/documents/download'
    | '/api/onboarding/submit'
    | '/api/trpc/$'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/verify-email/'
    | '/dashboard/'
    | '/deals/'
    | '/onboarding/'
    | '/$uid/'
    | '/api/documents/$documentId/status'
    | '/api/onboarding/$onboardingId/status'
    | '/admin/'
    | '/deals/$dealId/'
    | '/onboarding/edit/'
    | '/profile/$userId/'
    | '/profile/edit-onboarding/'
    | '/investments/$type/'
    | '/sectors/$sector/'
    | '/admin/compliance/'
    | '/admin/deals/'
    | '/admin/deals/$dealId/'
    | '/admin/deals/new/'
    | '/admin/compliance/investors/$id/'
    | '/admin/deals/$dealId/curate/'
    | '/admin/deals/$dealId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/'
    | '/slice-simulator'
    | '/api/auth/$'
    | '/api/documents/access'
    | '/api/documents/download'
    | '/api/onboarding/submit'
    | '/api/trpc/$'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/deals'
    | '/onboarding'
    | '/$uid'
    | '/api/documents/$documentId/status'
    | '/api/onboarding/$onboardingId/status'
    | '/admin'
    | '/deals/$dealId'
    | '/onboarding/edit'
    | '/profile/$userId'
    | '/profile/edit-onboarding'
    | '/investments/$type'
    | '/sectors/$sector'
    | '/admin/compliance'
    | '/admin/deals'
    | '/admin/deals/$dealId'
    | '/admin/deals/new'
    | '/admin/compliance/investors/$id'
    | '/admin/deals/$dealId/curate'
    | '/admin/deals/$dealId/edit'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(main-site)'
    | '/(dashboard)/(admin)'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/(main-site)/'
    | '/slice-simulator/'
    | '/api/auth/$'
    | '/api/documents/access'
    | '/api/documents/download'
    | '/api/onboarding/submit'
    | '/api/trpc/$'
    | '/(auth)/forgot-password/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(auth)/reset-password/'
    | '/(auth)/verify-email/'
    | '/(dashboard)/dashboard/'
    | '/(dashboard)/deals/'
    | '/(dashboard)/onboarding/'
    | '/(main-site)/$uid/'
    | '/api/documents/$documentId/status'
    | '/api/onboarding/$onboardingId/status'
    | '/(dashboard)/(admin)/admin/'
    | '/(dashboard)/deals/$dealId/'
    | '/(dashboard)/onboarding/edit/'
    | '/(dashboard)/profile/$userId/'
    | '/(dashboard)/profile/edit-onboarding/'
    | '/(main-site)/investments/$type/'
    | '/(main-site)/sectors/$sector/'
    | '/(dashboard)/(admin)/admin/compliance/'
    | '/(dashboard)/(admin)/admin/deals/'
    | '/(dashboard)/(admin)/admin/deals/$dealId/'
    | '/(dashboard)/(admin)/admin/deals/new/'
    | '/(dashboard)/(admin)/admin/compliance/investors/$id/'
    | '/(dashboard)/(admin)/admin/deals/$dealId/curate/'
    | '/(dashboard)/(admin)/admin/deals/$dealId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  mainSiteRouteRoute: typeof mainSiteRouteRouteWithChildren
  ApiExitPreviewRoute: typeof ApiExitPreviewRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  SliceSimulatorIndexRoute: typeof SliceSimulatorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsAccessRoute: typeof ApiDocumentsAccessRoute
  ApiDocumentsDownloadRoute: typeof ApiDocumentsDownloadRoute
  ApiOnboardingSubmitRoute: typeof ApiOnboardingSubmitRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiDocumentsDocumentIdStatusRoute: typeof ApiDocumentsDocumentIdStatusRoute
  ApiOnboardingOnboardingIdStatusRoute: typeof ApiOnboardingOnboardingIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main-site)': {
      id: '/(main-site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainSiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slice-simulator/': {
      id: '/slice-simulator/'
      path: '/slice-simulator'
      fullPath: '/slice-simulator/'
      preLoaderRoute: typeof SliceSimulatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main-site)/': {
      id: '/(main-site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainSiteIndexRouteImport
      parentRoute: typeof mainSiteRouteRoute
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exit-preview': {
      id: '/api/exit-preview'
      path: '/api/exit-preview'
      fullPath: '/api/exit-preview'
      preLoaderRoute: typeof ApiExitPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(admin)': {
      id: '/(dashboard)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardadminRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(main-site)/$uid/': {
      id: '/(main-site)/$uid/'
      path: '/$uid'
      fullPath: '/$uid/'
      preLoaderRoute: typeof mainSiteUidIndexRouteImport
      parentRoute: typeof mainSiteRouteRoute
    }
    '/(dashboard)/onboarding/': {
      id: '/(dashboard)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof dashboardOnboardingIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/deals/': {
      id: '/(dashboard)/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof dashboardDealsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/verify-email/': {
      id: '/(auth)/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof authVerifyEmailIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/submit': {
      id: '/api/onboarding/submit'
      path: '/api/onboarding/submit'
      fullPath: '/api/onboarding/submit'
      preLoaderRoute: typeof ApiOnboardingSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/download': {
      id: '/api/documents/download'
      path: '/api/documents/download'
      fullPath: '/api/documents/download'
      preLoaderRoute: typeof ApiDocumentsDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/access': {
      id: '/api/documents/access'
      path: '/api/documents/access'
      fullPath: '/api/documents/access'
      preLoaderRoute: typeof ApiDocumentsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main-site)/sectors/$sector/': {
      id: '/(main-site)/sectors/$sector/'
      path: '/sectors/$sector'
      fullPath: '/sectors/$sector/'
      preLoaderRoute: typeof mainSiteSectorsSectorIndexRouteImport
      parentRoute: typeof mainSiteRouteRoute
    }
    '/(main-site)/investments/$type/': {
      id: '/(main-site)/investments/$type/'
      path: '/investments/$type'
      fullPath: '/investments/$type/'
      preLoaderRoute: typeof mainSiteInvestmentsTypeIndexRouteImport
      parentRoute: typeof mainSiteRouteRoute
    }
    '/(dashboard)/profile/edit-onboarding/': {
      id: '/(dashboard)/profile/edit-onboarding/'
      path: '/profile/edit-onboarding'
      fullPath: '/profile/edit-onboarding/'
      preLoaderRoute: typeof dashboardProfileEditOnboardingIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/profile/$userId/': {
      id: '/(dashboard)/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof dashboardProfileUserIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/onboarding/edit/': {
      id: '/(dashboard)/onboarding/edit/'
      path: '/onboarding/edit'
      fullPath: '/onboarding/edit/'
      preLoaderRoute: typeof dashboardOnboardingEditIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/deals/$dealId/': {
      id: '/(dashboard)/deals/$dealId/'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId/'
      preLoaderRoute: typeof dashboardDealsDealIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/(admin)/admin/': {
      id: '/(dashboard)/(admin)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof dashboardadminAdminIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/api/onboarding/$onboardingId/status': {
      id: '/api/onboarding/$onboardingId/status'
      path: '/api/onboarding/$onboardingId/status'
      fullPath: '/api/onboarding/$onboardingId/status'
      preLoaderRoute: typeof ApiOnboardingOnboardingIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId/status': {
      id: '/api/documents/$documentId/status'
      path: '/api/documents/$documentId/status'
      fullPath: '/api/documents/$documentId/status'
      preLoaderRoute: typeof ApiDocumentsDocumentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(admin)/admin/deals/': {
      id: '/(dashboard)/(admin)/admin/deals/'
      path: '/admin/deals'
      fullPath: '/admin/deals/'
      preLoaderRoute: typeof dashboardadminAdminDealsIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/(dashboard)/(admin)/admin/compliance/': {
      id: '/(dashboard)/(admin)/admin/compliance/'
      path: '/admin/compliance'
      fullPath: '/admin/compliance/'
      preLoaderRoute: typeof dashboardadminAdminComplianceIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/(dashboard)/(admin)/admin/deals/new/': {
      id: '/(dashboard)/(admin)/admin/deals/new/'
      path: '/admin/deals/new'
      fullPath: '/admin/deals/new/'
      preLoaderRoute: typeof dashboardadminAdminDealsNewIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/(dashboard)/(admin)/admin/deals/$dealId/': {
      id: '/(dashboard)/(admin)/admin/deals/$dealId/'
      path: '/admin/deals/$dealId'
      fullPath: '/admin/deals/$dealId/'
      preLoaderRoute: typeof dashboardadminAdminDealsDealIdIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/(dashboard)/(admin)/admin/deals/$dealId/edit/': {
      id: '/(dashboard)/(admin)/admin/deals/$dealId/edit/'
      path: '/admin/deals/$dealId/edit'
      fullPath: '/admin/deals/$dealId/edit/'
      preLoaderRoute: typeof dashboardadminAdminDealsDealIdEditIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/(dashboard)/(admin)/admin/deals/$dealId/curate/': {
      id: '/(dashboard)/(admin)/admin/deals/$dealId/curate/'
      path: '/admin/deals/$dealId/curate'
      fullPath: '/admin/deals/$dealId/curate/'
      preLoaderRoute: typeof dashboardadminAdminDealsDealIdCurateIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
    '/(dashboard)/(admin)/admin/compliance/investors/$id/': {
      id: '/(dashboard)/(admin)/admin/compliance/investors/$id/'
      path: '/admin/compliance/investors/$id'
      fullPath: '/admin/compliance/investors/$id/'
      preLoaderRoute: typeof dashboardadminAdminComplianceInvestorsIdIndexRouteImport
      parentRoute: typeof dashboardadminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authVerifyEmailIndexRoute: typeof authVerifyEmailIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authVerifyEmailIndexRoute: authVerifyEmailIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardadminRouteRouteChildren {
  dashboardadminAdminIndexRoute: typeof dashboardadminAdminIndexRoute
  dashboardadminAdminComplianceIndexRoute: typeof dashboardadminAdminComplianceIndexRoute
  dashboardadminAdminDealsIndexRoute: typeof dashboardadminAdminDealsIndexRoute
  dashboardadminAdminDealsDealIdIndexRoute: typeof dashboardadminAdminDealsDealIdIndexRoute
  dashboardadminAdminDealsNewIndexRoute: typeof dashboardadminAdminDealsNewIndexRoute
  dashboardadminAdminComplianceInvestorsIdIndexRoute: typeof dashboardadminAdminComplianceInvestorsIdIndexRoute
  dashboardadminAdminDealsDealIdCurateIndexRoute: typeof dashboardadminAdminDealsDealIdCurateIndexRoute
  dashboardadminAdminDealsDealIdEditIndexRoute: typeof dashboardadminAdminDealsDealIdEditIndexRoute
}

const dashboardadminRouteRouteChildren: dashboardadminRouteRouteChildren = {
  dashboardadminAdminIndexRoute: dashboardadminAdminIndexRoute,
  dashboardadminAdminComplianceIndexRoute:
    dashboardadminAdminComplianceIndexRoute,
  dashboardadminAdminDealsIndexRoute: dashboardadminAdminDealsIndexRoute,
  dashboardadminAdminDealsDealIdIndexRoute:
    dashboardadminAdminDealsDealIdIndexRoute,
  dashboardadminAdminDealsNewIndexRoute: dashboardadminAdminDealsNewIndexRoute,
  dashboardadminAdminComplianceInvestorsIdIndexRoute:
    dashboardadminAdminComplianceInvestorsIdIndexRoute,
  dashboardadminAdminDealsDealIdCurateIndexRoute:
    dashboardadminAdminDealsDealIdCurateIndexRoute,
  dashboardadminAdminDealsDealIdEditIndexRoute:
    dashboardadminAdminDealsDealIdEditIndexRoute,
}

const dashboardadminRouteRouteWithChildren =
  dashboardadminRouteRoute._addFileChildren(dashboardadminRouteRouteChildren)

interface dashboardRouteRouteChildren {
  dashboardadminRouteRoute: typeof dashboardadminRouteRouteWithChildren
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
  dashboardDealsIndexRoute: typeof dashboardDealsIndexRoute
  dashboardOnboardingIndexRoute: typeof dashboardOnboardingIndexRoute
  dashboardDealsDealIdIndexRoute: typeof dashboardDealsDealIdIndexRoute
  dashboardOnboardingEditIndexRoute: typeof dashboardOnboardingEditIndexRoute
  dashboardProfileUserIdIndexRoute: typeof dashboardProfileUserIdIndexRoute
  dashboardProfileEditOnboardingIndexRoute: typeof dashboardProfileEditOnboardingIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardadminRouteRoute: dashboardadminRouteRouteWithChildren,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
  dashboardDealsIndexRoute: dashboardDealsIndexRoute,
  dashboardOnboardingIndexRoute: dashboardOnboardingIndexRoute,
  dashboardDealsDealIdIndexRoute: dashboardDealsDealIdIndexRoute,
  dashboardOnboardingEditIndexRoute: dashboardOnboardingEditIndexRoute,
  dashboardProfileUserIdIndexRoute: dashboardProfileUserIdIndexRoute,
  dashboardProfileEditOnboardingIndexRoute:
    dashboardProfileEditOnboardingIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface mainSiteRouteRouteChildren {
  mainSiteIndexRoute: typeof mainSiteIndexRoute
  mainSiteUidIndexRoute: typeof mainSiteUidIndexRoute
  mainSiteInvestmentsTypeIndexRoute: typeof mainSiteInvestmentsTypeIndexRoute
  mainSiteSectorsSectorIndexRoute: typeof mainSiteSectorsSectorIndexRoute
}

const mainSiteRouteRouteChildren: mainSiteRouteRouteChildren = {
  mainSiteIndexRoute: mainSiteIndexRoute,
  mainSiteUidIndexRoute: mainSiteUidIndexRoute,
  mainSiteInvestmentsTypeIndexRoute: mainSiteInvestmentsTypeIndexRoute,
  mainSiteSectorsSectorIndexRoute: mainSiteSectorsSectorIndexRoute,
}

const mainSiteRouteRouteWithChildren = mainSiteRouteRoute._addFileChildren(
  mainSiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  mainSiteRouteRoute: mainSiteRouteRouteWithChildren,
  ApiExitPreviewRoute: ApiExitPreviewRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  SliceSimulatorIndexRoute: SliceSimulatorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsAccessRoute: ApiDocumentsAccessRoute,
  ApiDocumentsDownloadRoute: ApiDocumentsDownloadRoute,
  ApiOnboardingSubmitRoute: ApiOnboardingSubmitRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiDocumentsDocumentIdStatusRoute: ApiDocumentsDocumentIdStatusRoute,
  ApiOnboardingOnboardingIdStatusRoute: ApiOnboardingOnboardingIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
