/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainSiteRouteRouteImport } from './routes/_main-site/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as ChatbotRouteRouteImport } from './routes/_chatbot/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as SliceSimulatorIndexRouteImport } from './routes/slice-simulator/index'
import { Route as MainSiteIndexRouteImport } from './routes/_main-site/index'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as ApiExitPreviewRouteImport } from './routes/api/exit-preview'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardAdminRouteRouteImport } from './routes/_dashboard/_admin/route'
import { Route as MainSiteUidIndexRouteImport } from './routes/_main-site/$uid/index'
import { Route as DashboardOnboardingIndexRouteImport } from './routes/_dashboard/onboarding/index'
import { Route as DashboardDealsIndexRouteImport } from './routes/_dashboard/deals/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ChatbotChatIndexRouteImport } from './routes/_chatbot/chat/index'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/_auth/verify-email/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiOnboardingSubmitRouteImport } from './routes/api/onboarding/submit'
import { Route as ApiDocumentsDownloadRouteImport } from './routes/api/documents/download'
import { Route as ApiDocumentsAccessRouteImport } from './routes/api/documents/access'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ChatbotChatChatIdRouteImport } from './routes/_chatbot/chat/$chatId'
import { Route as MainSiteSectorsSectorIndexRouteImport } from './routes/_main-site/sectors/$sector/index'
import { Route as MainSiteInvestmentsTypeIndexRouteImport } from './routes/_main-site/investments/$type/index'
import { Route as DashboardProfileEditOnboardingIndexRouteImport } from './routes/_dashboard/profile/edit-onboarding/index'
import { Route as DashboardProfileUserIdIndexRouteImport } from './routes/_dashboard/profile/$userId/index'
import { Route as DashboardOnboardingEditIndexRouteImport } from './routes/_dashboard/onboarding/edit/index'
import { Route as DashboardDealsDealIdIndexRouteImport } from './routes/_dashboard/deals/$dealId/index'
import { Route as DashboardAdminAdminIndexRouteImport } from './routes/_dashboard/_admin/admin/index'
import { Route as ApiOnboardingOnboardingIdStatusRouteImport } from './routes/api/onboarding/$onboardingId/status'
import { Route as ApiDocumentsDocumentIdStatusRouteImport } from './routes/api/documents/$documentId/status'
import { Route as DashboardAdminAdminDealsIndexRouteImport } from './routes/_dashboard/_admin/admin/deals/index'
import { Route as DashboardAdminAdminComplianceIndexRouteImport } from './routes/_dashboard/_admin/admin/compliance/index'
import { Route as DashboardAdminAdminDealsNewIndexRouteImport } from './routes/_dashboard/_admin/admin/deals/new/index'
import { Route as DashboardAdminAdminDealsDealIdIndexRouteImport } from './routes/_dashboard/_admin/admin/deals/$dealId/index'
import { Route as DashboardAdminAdminDealsDealIdEditIndexRouteImport } from './routes/_dashboard/_admin/admin/deals/$dealId/edit/index'
import { Route as DashboardAdminAdminDealsDealIdCurateIndexRouteImport } from './routes/_dashboard/_admin/admin/deals/$dealId/curate/index'
import { Route as DashboardAdminAdminComplianceInvestorsIdIndexRouteImport } from './routes/_dashboard/_admin/admin/compliance/investors/$id/index'

const MainSiteRouteRoute = MainSiteRouteRouteImport.update({
  id: '/_main-site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRouteRoute = ChatbotRouteRouteImport.update({
  id: '/_chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SliceSimulatorIndexRoute = SliceSimulatorIndexRouteImport.update({
  id: '/slice-simulator/',
  path: '/slice-simulator/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSiteIndexRoute = MainSiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainSiteRouteRoute,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExitPreviewRoute = ApiExitPreviewRouteImport.update({
  id: '/api/exit-preview',
  path: '/api/exit-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const MainSiteUidIndexRoute = MainSiteUidIndexRouteImport.update({
  id: '/$uid/',
  path: '/$uid/',
  getParentRoute: () => MainSiteRouteRoute,
} as any)
const DashboardOnboardingIndexRoute =
  DashboardOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDealsIndexRoute = DashboardDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ChatbotChatIndexRoute = ChatbotChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ChatbotRouteRoute,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingSubmitRoute = ApiOnboardingSubmitRouteImport.update({
  id: '/api/onboarding/submit',
  path: '/api/onboarding/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDownloadRoute = ApiDocumentsDownloadRouteImport.update({
  id: '/api/documents/download',
  path: '/api/documents/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsAccessRoute = ApiDocumentsAccessRouteImport.update({
  id: '/api/documents/access',
  path: '/api/documents/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotChatChatIdRoute = ChatbotChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => ChatbotRouteRoute,
} as any)
const MainSiteSectorsSectorIndexRoute =
  MainSiteSectorsSectorIndexRouteImport.update({
    id: '/sectors/$sector/',
    path: '/sectors/$sector/',
    getParentRoute: () => MainSiteRouteRoute,
  } as any)
const MainSiteInvestmentsTypeIndexRoute =
  MainSiteInvestmentsTypeIndexRouteImport.update({
    id: '/investments/$type/',
    path: '/investments/$type/',
    getParentRoute: () => MainSiteRouteRoute,
  } as any)
const DashboardProfileEditOnboardingIndexRoute =
  DashboardProfileEditOnboardingIndexRouteImport.update({
    id: '/profile/edit-onboarding/',
    path: '/profile/edit-onboarding/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileUserIdIndexRoute =
  DashboardProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOnboardingEditIndexRoute =
  DashboardOnboardingEditIndexRouteImport.update({
    id: '/onboarding/edit/',
    path: '/onboarding/edit/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDealsDealIdIndexRoute =
  DashboardDealsDealIdIndexRouteImport.update({
    id: '/deals/$dealId/',
    path: '/deals/$dealId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminAdminIndexRoute =
  DashboardAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const ApiOnboardingOnboardingIdStatusRoute =
  ApiOnboardingOnboardingIdStatusRouteImport.update({
    id: '/api/onboarding/$onboardingId/status',
    path: '/api/onboarding/$onboardingId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsDocumentIdStatusRoute =
  ApiDocumentsDocumentIdStatusRouteImport.update({
    id: '/api/documents/$documentId/status',
    path: '/api/documents/$documentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminAdminDealsIndexRoute =
  DashboardAdminAdminDealsIndexRouteImport.update({
    id: '/admin/deals/',
    path: '/admin/deals/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminComplianceIndexRoute =
  DashboardAdminAdminComplianceIndexRouteImport.update({
    id: '/admin/compliance/',
    path: '/admin/compliance/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminDealsNewIndexRoute =
  DashboardAdminAdminDealsNewIndexRouteImport.update({
    id: '/admin/deals/new/',
    path: '/admin/deals/new/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminDealsDealIdIndexRoute =
  DashboardAdminAdminDealsDealIdIndexRouteImport.update({
    id: '/admin/deals/$dealId/',
    path: '/admin/deals/$dealId/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminDealsDealIdEditIndexRoute =
  DashboardAdminAdminDealsDealIdEditIndexRouteImport.update({
    id: '/admin/deals/$dealId/edit/',
    path: '/admin/deals/$dealId/edit/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminDealsDealIdCurateIndexRoute =
  DashboardAdminAdminDealsDealIdCurateIndexRouteImport.update({
    id: '/admin/deals/$dealId/curate/',
    path: '/admin/deals/$dealId/curate/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAdminComplianceInvestorsIdIndexRoute =
  DashboardAdminAdminComplianceInvestorsIdIndexRouteImport.update({
    id: '/admin/compliance/investors/$id/',
    path: '/admin/compliance/investors/$id/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainSiteIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/slice-simulator/': typeof SliceSimulatorIndexRoute
  '/chat/$chatId': typeof ChatbotChatChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/access': typeof ApiDocumentsAccessRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/api/onboarding/submit': typeof ApiOnboardingSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/chat/': typeof ChatbotChatIndexRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/deals/': typeof DashboardDealsIndexRoute
  '/onboarding/': typeof DashboardOnboardingIndexRoute
  '/$uid/': typeof MainSiteUidIndexRoute
  '/api/documents/$documentId/status': typeof ApiDocumentsDocumentIdStatusRoute
  '/api/onboarding/$onboardingId/status': typeof ApiOnboardingOnboardingIdStatusRoute
  '/admin/': typeof DashboardAdminAdminIndexRoute
  '/deals/$dealId/': typeof DashboardDealsDealIdIndexRoute
  '/onboarding/edit/': typeof DashboardOnboardingEditIndexRoute
  '/profile/$userId/': typeof DashboardProfileUserIdIndexRoute
  '/profile/edit-onboarding/': typeof DashboardProfileEditOnboardingIndexRoute
  '/investments/$type/': typeof MainSiteInvestmentsTypeIndexRoute
  '/sectors/$sector/': typeof MainSiteSectorsSectorIndexRoute
  '/admin/compliance/': typeof DashboardAdminAdminComplianceIndexRoute
  '/admin/deals/': typeof DashboardAdminAdminDealsIndexRoute
  '/admin/deals/$dealId/': typeof DashboardAdminAdminDealsDealIdIndexRoute
  '/admin/deals/new/': typeof DashboardAdminAdminDealsNewIndexRoute
  '/admin/compliance/investors/$id/': typeof DashboardAdminAdminComplianceInvestorsIdIndexRoute
  '/admin/deals/$dealId/curate/': typeof DashboardAdminAdminDealsDealIdCurateIndexRoute
  '/admin/deals/$dealId/edit/': typeof DashboardAdminAdminDealsDealIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainSiteIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/slice-simulator': typeof SliceSimulatorIndexRoute
  '/chat/$chatId': typeof ChatbotChatChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/access': typeof ApiDocumentsAccessRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/api/onboarding/submit': typeof ApiOnboardingSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/verify-email': typeof AuthVerifyEmailIndexRoute
  '/chat': typeof ChatbotChatIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/deals': typeof DashboardDealsIndexRoute
  '/onboarding': typeof DashboardOnboardingIndexRoute
  '/$uid': typeof MainSiteUidIndexRoute
  '/api/documents/$documentId/status': typeof ApiDocumentsDocumentIdStatusRoute
  '/api/onboarding/$onboardingId/status': typeof ApiOnboardingOnboardingIdStatusRoute
  '/admin': typeof DashboardAdminAdminIndexRoute
  '/deals/$dealId': typeof DashboardDealsDealIdIndexRoute
  '/onboarding/edit': typeof DashboardOnboardingEditIndexRoute
  '/profile/$userId': typeof DashboardProfileUserIdIndexRoute
  '/profile/edit-onboarding': typeof DashboardProfileEditOnboardingIndexRoute
  '/investments/$type': typeof MainSiteInvestmentsTypeIndexRoute
  '/sectors/$sector': typeof MainSiteSectorsSectorIndexRoute
  '/admin/compliance': typeof DashboardAdminAdminComplianceIndexRoute
  '/admin/deals': typeof DashboardAdminAdminDealsIndexRoute
  '/admin/deals/$dealId': typeof DashboardAdminAdminDealsDealIdIndexRoute
  '/admin/deals/new': typeof DashboardAdminAdminDealsNewIndexRoute
  '/admin/compliance/investors/$id': typeof DashboardAdminAdminComplianceInvestorsIdIndexRoute
  '/admin/deals/$dealId/curate': typeof DashboardAdminAdminDealsDealIdCurateIndexRoute
  '/admin/deals/$dealId/edit': typeof DashboardAdminAdminDealsDealIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_chatbot': typeof ChatbotRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_main-site': typeof MainSiteRouteRouteWithChildren
  '/_dashboard/_admin': typeof DashboardAdminRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/exit-preview': typeof ApiExitPreviewRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/_main-site/': typeof MainSiteIndexRoute
  '/slice-simulator/': typeof SliceSimulatorIndexRoute
  '/_chatbot/chat/$chatId': typeof ChatbotChatChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/access': typeof ApiDocumentsAccessRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/api/onboarding/submit': typeof ApiOnboardingSubmitRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/_chatbot/chat/': typeof ChatbotChatIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/deals/': typeof DashboardDealsIndexRoute
  '/_dashboard/onboarding/': typeof DashboardOnboardingIndexRoute
  '/_main-site/$uid/': typeof MainSiteUidIndexRoute
  '/api/documents/$documentId/status': typeof ApiDocumentsDocumentIdStatusRoute
  '/api/onboarding/$onboardingId/status': typeof ApiOnboardingOnboardingIdStatusRoute
  '/_dashboard/_admin/admin/': typeof DashboardAdminAdminIndexRoute
  '/_dashboard/deals/$dealId/': typeof DashboardDealsDealIdIndexRoute
  '/_dashboard/onboarding/edit/': typeof DashboardOnboardingEditIndexRoute
  '/_dashboard/profile/$userId/': typeof DashboardProfileUserIdIndexRoute
  '/_dashboard/profile/edit-onboarding/': typeof DashboardProfileEditOnboardingIndexRoute
  '/_main-site/investments/$type/': typeof MainSiteInvestmentsTypeIndexRoute
  '/_main-site/sectors/$sector/': typeof MainSiteSectorsSectorIndexRoute
  '/_dashboard/_admin/admin/compliance/': typeof DashboardAdminAdminComplianceIndexRoute
  '/_dashboard/_admin/admin/deals/': typeof DashboardAdminAdminDealsIndexRoute
  '/_dashboard/_admin/admin/deals/$dealId/': typeof DashboardAdminAdminDealsDealIdIndexRoute
  '/_dashboard/_admin/admin/deals/new/': typeof DashboardAdminAdminDealsNewIndexRoute
  '/_dashboard/_admin/admin/compliance/investors/$id/': typeof DashboardAdminAdminComplianceInvestorsIdIndexRoute
  '/_dashboard/_admin/admin/deals/$dealId/curate/': typeof DashboardAdminAdminDealsDealIdCurateIndexRoute
  '/_dashboard/_admin/admin/deals/$dealId/edit/': typeof DashboardAdminAdminDealsDealIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/slice-simulator/'
    | '/chat/$chatId'
    | '/api/auth/$'
    | '/api/documents/access'
    | '/api/documents/download'
    | '/api/onboarding/submit'
    | '/api/trpc/$'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/verify-email/'
    | '/chat/'
    | '/dashboard/'
    | '/deals/'
    | '/onboarding/'
    | '/$uid/'
    | '/api/documents/$documentId/status'
    | '/api/onboarding/$onboardingId/status'
    | '/admin/'
    | '/deals/$dealId/'
    | '/onboarding/edit/'
    | '/profile/$userId/'
    | '/profile/edit-onboarding/'
    | '/investments/$type/'
    | '/sectors/$sector/'
    | '/admin/compliance/'
    | '/admin/deals/'
    | '/admin/deals/$dealId/'
    | '/admin/deals/new/'
    | '/admin/compliance/investors/$id/'
    | '/admin/deals/$dealId/curate/'
    | '/admin/deals/$dealId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/slice-simulator'
    | '/chat/$chatId'
    | '/api/auth/$'
    | '/api/documents/access'
    | '/api/documents/download'
    | '/api/onboarding/submit'
    | '/api/trpc/$'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/chat'
    | '/dashboard'
    | '/deals'
    | '/onboarding'
    | '/$uid'
    | '/api/documents/$documentId/status'
    | '/api/onboarding/$onboardingId/status'
    | '/admin'
    | '/deals/$dealId'
    | '/onboarding/edit'
    | '/profile/$userId'
    | '/profile/edit-onboarding'
    | '/investments/$type'
    | '/sectors/$sector'
    | '/admin/compliance'
    | '/admin/deals'
    | '/admin/deals/$dealId'
    | '/admin/deals/new'
    | '/admin/compliance/investors/$id'
    | '/admin/deals/$dealId/curate'
    | '/admin/deals/$dealId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_chatbot'
    | '/_dashboard'
    | '/_main-site'
    | '/_dashboard/_admin'
    | '/api/chat'
    | '/api/exit-preview'
    | '/api/preview'
    | '/api/revalidate'
    | '/_main-site/'
    | '/slice-simulator/'
    | '/_chatbot/chat/$chatId'
    | '/api/auth/$'
    | '/api/documents/access'
    | '/api/documents/download'
    | '/api/onboarding/submit'
    | '/api/trpc/$'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_auth/reset-password/'
    | '/_auth/verify-email/'
    | '/_chatbot/chat/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/deals/'
    | '/_dashboard/onboarding/'
    | '/_main-site/$uid/'
    | '/api/documents/$documentId/status'
    | '/api/onboarding/$onboardingId/status'
    | '/_dashboard/_admin/admin/'
    | '/_dashboard/deals/$dealId/'
    | '/_dashboard/onboarding/edit/'
    | '/_dashboard/profile/$userId/'
    | '/_dashboard/profile/edit-onboarding/'
    | '/_main-site/investments/$type/'
    | '/_main-site/sectors/$sector/'
    | '/_dashboard/_admin/admin/compliance/'
    | '/_dashboard/_admin/admin/deals/'
    | '/_dashboard/_admin/admin/deals/$dealId/'
    | '/_dashboard/_admin/admin/deals/new/'
    | '/_dashboard/_admin/admin/compliance/investors/$id/'
    | '/_dashboard/_admin/admin/deals/$dealId/curate/'
    | '/_dashboard/_admin/admin/deals/$dealId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ChatbotRouteRoute: typeof ChatbotRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MainSiteRouteRoute: typeof MainSiteRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiExitPreviewRoute: typeof ApiExitPreviewRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  SliceSimulatorIndexRoute: typeof SliceSimulatorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsAccessRoute: typeof ApiDocumentsAccessRoute
  ApiDocumentsDownloadRoute: typeof ApiDocumentsDownloadRoute
  ApiOnboardingSubmitRoute: typeof ApiOnboardingSubmitRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiDocumentsDocumentIdStatusRoute: typeof ApiDocumentsDocumentIdStatusRoute
  ApiOnboardingOnboardingIdStatusRoute: typeof ApiOnboardingOnboardingIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-site': {
      id: '/_main-site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainSiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chatbot': {
      id: '/_chatbot'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatbotRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slice-simulator/': {
      id: '/slice-simulator/'
      path: '/slice-simulator'
      fullPath: '/slice-simulator/'
      preLoaderRoute: typeof SliceSimulatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-site/': {
      id: '/_main-site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainSiteIndexRouteImport
      parentRoute: typeof MainSiteRouteRoute
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exit-preview': {
      id: '/api/exit-preview'
      path: '/api/exit-preview'
      fullPath: '/api/exit-preview'
      preLoaderRoute: typeof ApiExitPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_admin': {
      id: '/_dashboard/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_main-site/$uid/': {
      id: '/_main-site/$uid/'
      path: '/$uid'
      fullPath: '/$uid/'
      preLoaderRoute: typeof MainSiteUidIndexRouteImport
      parentRoute: typeof MainSiteRouteRoute
    }
    '/_dashboard/onboarding/': {
      id: '/_dashboard/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof DashboardOnboardingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/deals/': {
      id: '/_dashboard/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DashboardDealsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_chatbot/chat/': {
      id: '/_chatbot/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatbotChatIndexRouteImport
      parentRoute: typeof ChatbotRouteRoute
    }
    '/_auth/verify-email/': {
      id: '/_auth/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/submit': {
      id: '/api/onboarding/submit'
      path: '/api/onboarding/submit'
      fullPath: '/api/onboarding/submit'
      preLoaderRoute: typeof ApiOnboardingSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/download': {
      id: '/api/documents/download'
      path: '/api/documents/download'
      fullPath: '/api/documents/download'
      preLoaderRoute: typeof ApiDocumentsDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/access': {
      id: '/api/documents/access'
      path: '/api/documents/access'
      fullPath: '/api/documents/access'
      preLoaderRoute: typeof ApiDocumentsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chatbot/chat/$chatId': {
      id: '/_chatbot/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatbotChatChatIdRouteImport
      parentRoute: typeof ChatbotRouteRoute
    }
    '/_main-site/sectors/$sector/': {
      id: '/_main-site/sectors/$sector/'
      path: '/sectors/$sector'
      fullPath: '/sectors/$sector/'
      preLoaderRoute: typeof MainSiteSectorsSectorIndexRouteImport
      parentRoute: typeof MainSiteRouteRoute
    }
    '/_main-site/investments/$type/': {
      id: '/_main-site/investments/$type/'
      path: '/investments/$type'
      fullPath: '/investments/$type/'
      preLoaderRoute: typeof MainSiteInvestmentsTypeIndexRouteImport
      parentRoute: typeof MainSiteRouteRoute
    }
    '/_dashboard/profile/edit-onboarding/': {
      id: '/_dashboard/profile/edit-onboarding/'
      path: '/profile/edit-onboarding'
      fullPath: '/profile/edit-onboarding/'
      preLoaderRoute: typeof DashboardProfileEditOnboardingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile/$userId/': {
      id: '/_dashboard/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof DashboardProfileUserIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/onboarding/edit/': {
      id: '/_dashboard/onboarding/edit/'
      path: '/onboarding/edit'
      fullPath: '/onboarding/edit/'
      preLoaderRoute: typeof DashboardOnboardingEditIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/deals/$dealId/': {
      id: '/_dashboard/deals/$dealId/'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId/'
      preLoaderRoute: typeof DashboardDealsDealIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/_admin/admin/': {
      id: '/_dashboard/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/onboarding/$onboardingId/status': {
      id: '/api/onboarding/$onboardingId/status'
      path: '/api/onboarding/$onboardingId/status'
      fullPath: '/api/onboarding/$onboardingId/status'
      preLoaderRoute: typeof ApiOnboardingOnboardingIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId/status': {
      id: '/api/documents/$documentId/status'
      path: '/api/documents/$documentId/status'
      fullPath: '/api/documents/$documentId/status'
      preLoaderRoute: typeof ApiDocumentsDocumentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_admin/admin/deals/': {
      id: '/_dashboard/_admin/admin/deals/'
      path: '/admin/deals'
      fullPath: '/admin/deals/'
      preLoaderRoute: typeof DashboardAdminAdminDealsIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/_admin/admin/compliance/': {
      id: '/_dashboard/_admin/admin/compliance/'
      path: '/admin/compliance'
      fullPath: '/admin/compliance/'
      preLoaderRoute: typeof DashboardAdminAdminComplianceIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/_admin/admin/deals/new/': {
      id: '/_dashboard/_admin/admin/deals/new/'
      path: '/admin/deals/new'
      fullPath: '/admin/deals/new/'
      preLoaderRoute: typeof DashboardAdminAdminDealsNewIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/_admin/admin/deals/$dealId/': {
      id: '/_dashboard/_admin/admin/deals/$dealId/'
      path: '/admin/deals/$dealId'
      fullPath: '/admin/deals/$dealId/'
      preLoaderRoute: typeof DashboardAdminAdminDealsDealIdIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/_admin/admin/deals/$dealId/edit/': {
      id: '/_dashboard/_admin/admin/deals/$dealId/edit/'
      path: '/admin/deals/$dealId/edit'
      fullPath: '/admin/deals/$dealId/edit/'
      preLoaderRoute: typeof DashboardAdminAdminDealsDealIdEditIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/_admin/admin/deals/$dealId/curate/': {
      id: '/_dashboard/_admin/admin/deals/$dealId/curate/'
      path: '/admin/deals/$dealId/curate'
      fullPath: '/admin/deals/$dealId/curate/'
      preLoaderRoute: typeof DashboardAdminAdminDealsDealIdCurateIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/_admin/admin/compliance/investors/$id/': {
      id: '/_dashboard/_admin/admin/compliance/investors/$id/'
      path: '/admin/compliance/investors/$id'
      fullPath: '/admin/compliance/investors/$id/'
      preLoaderRoute: typeof DashboardAdminAdminComplianceInvestorsIdIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ChatbotRouteRouteChildren {
  ChatbotChatChatIdRoute: typeof ChatbotChatChatIdRoute
  ChatbotChatIndexRoute: typeof ChatbotChatIndexRoute
}

const ChatbotRouteRouteChildren: ChatbotRouteRouteChildren = {
  ChatbotChatChatIdRoute: ChatbotChatChatIdRoute,
  ChatbotChatIndexRoute: ChatbotChatIndexRoute,
}

const ChatbotRouteRouteWithChildren = ChatbotRouteRoute._addFileChildren(
  ChatbotRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminAdminIndexRoute: typeof DashboardAdminAdminIndexRoute
  DashboardAdminAdminComplianceIndexRoute: typeof DashboardAdminAdminComplianceIndexRoute
  DashboardAdminAdminDealsIndexRoute: typeof DashboardAdminAdminDealsIndexRoute
  DashboardAdminAdminDealsDealIdIndexRoute: typeof DashboardAdminAdminDealsDealIdIndexRoute
  DashboardAdminAdminDealsNewIndexRoute: typeof DashboardAdminAdminDealsNewIndexRoute
  DashboardAdminAdminComplianceInvestorsIdIndexRoute: typeof DashboardAdminAdminComplianceInvestorsIdIndexRoute
  DashboardAdminAdminDealsDealIdCurateIndexRoute: typeof DashboardAdminAdminDealsDealIdCurateIndexRoute
  DashboardAdminAdminDealsDealIdEditIndexRoute: typeof DashboardAdminAdminDealsDealIdEditIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminAdminIndexRoute: DashboardAdminAdminIndexRoute,
  DashboardAdminAdminComplianceIndexRoute:
    DashboardAdminAdminComplianceIndexRoute,
  DashboardAdminAdminDealsIndexRoute: DashboardAdminAdminDealsIndexRoute,
  DashboardAdminAdminDealsDealIdIndexRoute:
    DashboardAdminAdminDealsDealIdIndexRoute,
  DashboardAdminAdminDealsNewIndexRoute: DashboardAdminAdminDealsNewIndexRoute,
  DashboardAdminAdminComplianceInvestorsIdIndexRoute:
    DashboardAdminAdminComplianceInvestorsIdIndexRoute,
  DashboardAdminAdminDealsDealIdCurateIndexRoute:
    DashboardAdminAdminDealsDealIdCurateIndexRoute,
  DashboardAdminAdminDealsDealIdEditIndexRoute:
    DashboardAdminAdminDealsDealIdEditIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDealsIndexRoute: typeof DashboardDealsIndexRoute
  DashboardOnboardingIndexRoute: typeof DashboardOnboardingIndexRoute
  DashboardDealsDealIdIndexRoute: typeof DashboardDealsDealIdIndexRoute
  DashboardOnboardingEditIndexRoute: typeof DashboardOnboardingEditIndexRoute
  DashboardProfileUserIdIndexRoute: typeof DashboardProfileUserIdIndexRoute
  DashboardProfileEditOnboardingIndexRoute: typeof DashboardProfileEditOnboardingIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDealsIndexRoute: DashboardDealsIndexRoute,
  DashboardOnboardingIndexRoute: DashboardOnboardingIndexRoute,
  DashboardDealsDealIdIndexRoute: DashboardDealsDealIdIndexRoute,
  DashboardOnboardingEditIndexRoute: DashboardOnboardingEditIndexRoute,
  DashboardProfileUserIdIndexRoute: DashboardProfileUserIdIndexRoute,
  DashboardProfileEditOnboardingIndexRoute:
    DashboardProfileEditOnboardingIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MainSiteRouteRouteChildren {
  MainSiteIndexRoute: typeof MainSiteIndexRoute
  MainSiteUidIndexRoute: typeof MainSiteUidIndexRoute
  MainSiteInvestmentsTypeIndexRoute: typeof MainSiteInvestmentsTypeIndexRoute
  MainSiteSectorsSectorIndexRoute: typeof MainSiteSectorsSectorIndexRoute
}

const MainSiteRouteRouteChildren: MainSiteRouteRouteChildren = {
  MainSiteIndexRoute: MainSiteIndexRoute,
  MainSiteUidIndexRoute: MainSiteUidIndexRoute,
  MainSiteInvestmentsTypeIndexRoute: MainSiteInvestmentsTypeIndexRoute,
  MainSiteSectorsSectorIndexRoute: MainSiteSectorsSectorIndexRoute,
}

const MainSiteRouteRouteWithChildren = MainSiteRouteRoute._addFileChildren(
  MainSiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ChatbotRouteRoute: ChatbotRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MainSiteRouteRoute: MainSiteRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiExitPreviewRoute: ApiExitPreviewRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  SliceSimulatorIndexRoute: SliceSimulatorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsAccessRoute: ApiDocumentsAccessRoute,
  ApiDocumentsDownloadRoute: ApiDocumentsDownloadRoute,
  ApiOnboardingSubmitRoute: ApiOnboardingSubmitRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiDocumentsDocumentIdStatusRoute: ApiDocumentsDocumentIdStatusRoute,
  ApiOnboardingOnboardingIdStatusRoute: ApiOnboardingOnboardingIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
