// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_heading: dynamic(() => import("./ContentHeading")),
  cta: dynamic(() => import("./Cta")),
  hero: dynamic(() => import("./Hero")),
  hero_image_background: dynamic(() => import("./HeroImageBackground")),
  hero_with_quote: dynamic(() => import("./HeroWithQuote")),
  image_heading_toggle: dynamic(() => import("./ImageHeadingToggle")),
  investment_hero: dynamic(() => import("./InvestmentHero")),
  investment_timeline: dynamic(() => import("./InvestmentTimeline")),
  meet_team: dynamic(() => import("./MeetTeam")),
  muted_background_content: dynamic(() => import("./MutedBackgroundContent")),
  reuseable_cards: dynamic(() => import("./ReuseableCards")),
  rounded_image_content: dynamic(() => import("./RoundedImageContent")),
  scroll_cards: dynamic(() => import("./ScrollCards")),
  sector_expertise: dynamic(() => import("./SectorExpertise")),
  side_heading_content: dynamic(() => import("./SideHeadingContent")),
  step_journey: dynamic(() => import("./StepJourney")),
  story_testimonials: dynamic(() => import("./StoryTestimonials")),
  three_content_cards: dynamic(() => import("./ThreeContentCards")),
  three_round_images: dynamic(() => import("./ThreeRoundImages")),
  updated_hero_section: dynamic(() => import("./UpdatedHeroSection")),
  value_creation_playbook: dynamic(() => import("./ValueCreationPlaybook")),
};
